// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOoutfwj-d3_FwtFHa48f1ML6dmNO9s6U',
    appId: '1:228569454694:web:043fdda6ad1c3d325775a7',
    messagingSenderId: '228569454694',
    projectId: 'pic2plate-ccd98',
    authDomain: 'pic2plate-ccd98.firebaseapp.com',
    storageBucket: 'pic2plate-ccd98.firebasestorage.app',
    measurementId: 'G-N1X2J3GNV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6y4gFOC3M4CY6iZvFXuXTQYWAxR8KCbo',
    appId: '1:228569454694:android:3ace1ce0845d04955775a7',
    messagingSenderId: '228569454694',
    projectId: 'pic2plate-ccd98',
    storageBucket: 'pic2plate-ccd98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbBEENdX3wvrN_oKizDjcFFuaGsWOyFU4',
    appId: '1:228569454694:ios:c049ddca756144425775a7',
    messagingSenderId: '228569454694',
    projectId: 'pic2plate-ccd98',
    storageBucket: 'pic2plate-ccd98.firebasestorage.app',
    iosBundleId: 'com.tarapalmier.projectPic2plate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbBEENdX3wvrN_oKizDjcFFuaGsWOyFU4',
    appId: '1:228569454694:ios:ca33b0867a0660125775a7',
    messagingSenderId: '228569454694',
    projectId: 'pic2plate-ccd98',
    storageBucket: 'pic2plate-ccd98.firebasestorage.app',
    iosBundleId: 'com.example.projectPic2plate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOoutfwj-d3_FwtFHa48f1ML6dmNO9s6U',
    appId: '1:228569454694:web:c7e7a26cbb6521845775a7',
    messagingSenderId: '228569454694',
    projectId: 'pic2plate-ccd98',
    authDomain: 'pic2plate-ccd98.firebaseapp.com',
    storageBucket: 'pic2plate-ccd98.firebasestorage.app',
    measurementId: 'G-0HFKF1QB4R',
  );
}
